### ISSUE TITLE
New website for kpt

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#1160]
This is the epic for creating a new website for kpt, for details please see the content roadmap document.

- [x] Research various developer tool documentation frameworks (such as docsify)
- [x] Create a prototype of a help website for kpt with a few pages to demo the functionality and the update process
- [x] Reserve the domain for kpt
- [x] Create an information architecture document
- [x] Automate build pipeline for site

**Comment by mikebz** [comment]
Preview is here: https://kpt-dev-ee2a9.web.app/

**Comment by mikebz** [comment]
@etefera are you blocked by the review?  Do we have the layout with MD docs all done?

**Comment by mikebz** [comment]
is there a way to add a 3rd level of commands so under cfg I can see all of the commands that are available?  https://kpt-dev-ee2a9.web.app/reference/cfg?id=create-subst - the anchor is there but I have to scroll through a long page to see what's available.
