### ISSUE TITLE
Epic: Kpt hydration detailed design

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1195]
Write a design document for Kpt Hydration

- [x] Pipeline schema
- [x] Pkg hydration core machinery
- [x] Imperative function run
- [ ] Metafunction support
- [ ] Permission Design
- [ ] Setters Design https://github.com/GoogleContainerTools/kpt/issues/1281
- [ ] CLI UX design
