### ISSUE TITLE
Epic: Implement Pipeline schema

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1278]
Following tasks need to be accomplished as part of this umbrella issue:

- [ ] Move the current design (go/kpt-pipeline-declaration) to a kpt repo in design dir
- [x] Pipeline struct and auxiliary structs (KRM function and args) definition #1286 #1288 
- [x] Read/Write API for the pipeline struct #1304 #1310
- [x] Validate pipeline schema #1331 #1339
- [x] Unit tests for pipeline I/O
- [ ] Support for resolving the default image path for kpt functions #1333 [P1]
