### ISSUE TITLE
Umbrella issue: Implement pipeline executor

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1279]
Following tasks need to be accomplished as part of this umbrella issue.

- [ ] Core hydration DAG machinery (without setters): This involves reading the pipeline, invoking different function groups, function execution with the args from pipeline, default image path resolution, recursive hydration, resources input/output chains, leaf level hydration etc.
- [ ] e2e test for pipeline executor
- [ ] In-place sink-mode with merge as default  Merge strategy

**Comment by frankfarzan** [comment]
Closing this since the remaining issue is tracked as well.
