### ISSUE TITLE
Kpt Fn Catalog Doc Umbrella Issue

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1489]
We need to finish the followings for the new kpt fn catalog doc site

- [x] The site should be served at `catalog.kpt.dev` subdomain
- [x] We will not support explicit categories. Instead each function will have tags (e.g. mutator, validator and etc).
- [x] We should use the new registries (kpt-fn, kpt-fn-contrib) instead of the old registry (kpt-functions) in the doc and examples.
- [x] Random functions in the existing catalog site should be removed.
- [x] Each function and its doc are independently versioned.
- [x] Each function should have its own usage doc. They should be consistent.
- [x] Every function should have one or more examples. Examples should be consistent.
- [x] On each OSS function's page, there should be a link to that function's source.
- [x] On each function's page, there should be a button linking to Kpt GitHub issue filing like the buttons on the top right in https://kubernetes.io/docs/concepts/workloads/
- [x] CD pipeline for the site.

Please feel free to update the list.

**Comment by mikebz** [comment]
Question: why do we want to have a subdomain here?  Why not just have the catalog as one of the pages?  My concern here is that we are creating infrastructure for what is now a fairly limited set of functions (I'd say anything less than 50 is probably OK to be updated by hand).  

We need to de-risk the layout and ability to find the right functions with the small amount of functions that we have.

**Comment by mengqiy** [comment]
We want to use a subdomain since these 2 sites are independently managed and deployed. Using a subdomain can make things much easier.

What I imagine is that:
When visiting `kpt.dev` site, in the vertical sidebar navigation menu, we have a top level item called `Function Catalog` that points to the subdomain while we will NOT have any subitems. The layout looks like this:
```
Home
Command Reference
  cfg
  fn
  live
  pkg
Tutorials
  Deploy CockroachDB
  Set up Kafka with Helm-inflator
  Integrate with CI/CD pipeline
Function Catalog # No subitems here. It points to the subdomain.
Guides
About
  Design
FAQ
Contact Us
```

When visiting `catalog.kpt.dev` site, in the vertical sidebar navigation menu, only Function Catalog will have subitems, others will only have top level item. The layout looks like this:
```
Home   # these top level items points to the right location in kpt.dev site
Command Reference
Tutorials
Function Catalog
  Mutators
  Validators
Guides
About
FAQ
Contact Us
```

In this way, the 2 sites looks like one site. And the discoverability should also be good enough.

**Comment by frankfarzan** [comment]
@mengqiy As part of this, we should do a quick UI mock for a function.
