### ISSUE TITLE
Epic: Imperative function workflow changes for v1

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1494]
This is an umbrella issue to track the changes we want to run for running functions imperatively for `v1`.

- [x] Identify features to deprecate/drop from current command with the introduction of `pipeline` #1501 
- [x] Come up with plan to reorganize the code across `kyaml`, `kpt` #1519 
- [x] Refactor the code in kpt/kyaml (especially code that is coupled with the kpt CLI) #1547
- [x] Drop declarative function support #1547
- [x] Drop starlark support #1547
- [x] Metafunction support #1202 
- [x] Support for StandardResult #1390 
- [x] Out-of-place support
- [x] Support for excluding function configs referred in the pipeline #1670

**Comment by mikebz** [comment]
@droot can we add the child issues to the original comment and maybe have them as a check list?
Thank you!

**Comment by droot** [comment]
Added the checklist with some more details. Added issue for in-progress work. Will be adding more issues as we go along.
