### ISSUE TITLE
Epic: Kpt OpenAPI roadmap

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#1521]
This is an umbrella issue describing the tasks that @mengqiy outlined, for OpenAPI features in kpt

- [ ] Define a scheme to use OpenAPI extension mechanisms #1505 
- [ ] Use the scheme to define the augment for k8s builtin types
- [ ] Use the scheme to define the augment for KCC types
- [ ] Kpt should have one or more compiled-in OpenAPI docs that matches the minor versions supported by GKE fleet
- [ ] Kpt should allow users to provide OpenAPI docs
- [ ] Kpt should be able to load the OpenAPI from the APIServer
- [ ] Ensure “kpt pkg update” can access the merge strategy and merge keys from the OpenAPI doc
- [ ] No matter what language a function is written in, kpt should have a mechanism to inject the OpenAPI document to a function when it is executed
- [ ] Ensure functions in the catalog works well

**Comment by natasha41575** [comment]
@mengqiy umbrella issue for the openapi work

**Comment by natasha41575** [comment]
we may also want to look into https://github.com/kubernetes-sigs/kustomize/issues/3670

**Comment by mikebz** [comment]
I'd consider moving this into "In Progress" if it's actively being worked on.

**Comment by mikebz** [comment]
Could we link some questions or issues that were filed because this feature didn't exist?  It would be great to get back to those users and see if we are addressing their needs and also could be early design partners.

**Comment by natasha41575** [comment]
I will link issues if they arise. The main goal here is to make sure the UX for functions is good, so we are welcoming any input from users on that.

**Comment by mikebz** [comment]
I have rarely seen a feature well received if it wasn't addressing a problem that customers already knew they had.

**Comment by frankfarzan** [comment]
This is a cross-cutting and critical part of having good UX when manipulating KRM resources. Even most basic functions like name-prefix require augmented OpenAPI semantics to work properly. Kustomize has done this for core k8s native types based on a real need, we need to generalize and extend this.
