### ISSUE TITLE
Site infra

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1575]
Tracking issue for site infrastructure and look and feel:

- [x] Page navigation #1574
- [x] Section page rendering #1569
- [x] Demo videos are not rendered #1578
- [x] Shell block syntax highlighting #1579
- [x] Styling for selected navbar item is too subtle #1580
- [x] Don't auto expand navbar sections #1603

**Comment by mikebz** [comment]
@etefera when you triage an issue please add it to the project.  Done here, just makes sure these are not lost in the future.
