### ISSUE TITLE
kpt v1 docs

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1576]
- [x] references
  - [x] pkg: #1570
  - [x] fn:  #1571
  - [x] live: #1572
  - [x] CLI usability changes: #1577
- [x] book: #1573
- [x] Migrate catalog functions example to use kpt 1.0 CLI #1548
- [ ] Complete and polish function catalog docs #1890
- [x] site infra: #1575
- [x] function catalog infra: #1465
