### ISSUE TITLE
CLI usability: reference docs consistency

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1577]
As part of CLI usability, commands are removed, moved to a different group, renamed, etc. This issue covers the cross-cutting changes to command reference to ensure consistency. Each command group has a separate issue (#1576) for addressing the content changes which is out of scope for this issue.

- [x] Ensure every CLI command has a corresponding reference doc
- [x] Prune deleted commands
- [x] Ensure renames are reflected in the docs
- [x] Ensure cross-cutting CLI changes (e.g. PKG_PATH, stdin) are reflects in the docs
- [x] Audit all commands and their flags/args for consistency. Do not print duplicate flags section.
- [x] Commands should always be in lower-case: `cat` not `Cat`: https://googlecontainertools.github.io/kpt/reference/cfg/cat/
- [x] Remove doc for command groups e.g. https://googlecontainertools.github.io/kpt/reference/pkg/. These pages mostly duplicate content appropriate for the book. Reference docs should describe a specific command in a succinct and precise manner.
- [x] Remove demo videos. See #1654
- [x] Standardize use of `Synopsis`, `Args`, `Flags`, `Examples` sections and their ordering. Compare the following:
https://googlecontainertools.github.io/kpt/reference/pkg/diff/
https://googlecontainertools.github.io/kpt/reference/pkg/get/

**Comment by frankfarzan** [comment]
Also, let's delete the From/To tables:

https://screenshot.googleplex.com/4dVNty7YYnDrp68

They're not comprehensible.
