### ISSUE TITLE
CLI usability: Implementation

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1644]
Tracking all the changes from the design.

- [x] Design: kpt CLI Usability (https://github.com/GoogleContainerTools/kpt/issues/1495)
- [x] Remove cfg command group and clean-up (https://github.com/GoogleContainerTools/kpt/issues/1517)
- [x] Delete desc, setters and search commands related code and cleanup (https://github.com/GoogleContainerTools/kpt/pull/1597)
- [x] Make DIR optional for pkg commands and cleanup (https://github.com/GoogleContainerTools/kpt/pull/1534)
- [x] Make DIR optional for live commands (https://github.com/GoogleContainerTools/kpt/issues/1592)
- [x] Make DIR optional for fn commands (https://github.com/GoogleContainerTools/kpt/pull/1710)
- [x] kpt pkg cat clean-up (https://github.com/GoogleContainerTools/kpt/pull/1624)
