### ISSUE TITLE
Improve Test Coverage for kpt Package Diff

### ISSUE THREAD

**Issue by runewake2** [GoogleContainerTools/kpt#1776]
- [x] Kptfile has diff when pipeline changes are made (#1777)
- [x] Running a diff against a directory which does not contain a Kptfile (empty dir) (#1914)
- [x] Running a diff against a directory which does not exist (#1914)
- [x] Running a diff when an invalid git ref is provided (#1914)
- [x] Running a 3 way diff provides three parameters to the diff command (#1914)
