### ISSUE TITLE
Epic: Migrate critical packages to kpt 1.0

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1834]
- [x] POC on Blueprints Controller, Landing Zone packages migration
- [x] Design proposal for e2e path to migrate existing kpt packages to make them compatible with kpt 1.0
- [x] Implement helper function(gcr.io/kpt-fn/fix) to help with [automated portion](https://kpt.dev/installation/migration?id=automated-portion-of-migration) of migration.
- [x] Document end to end migration steps (https://kpt.dev/installation/migration)

Related issues:
- [x] https://github.com/GoogleContainerTools/kpt/issues/2094
- [x] https://github.com/GoogleContainerTools/kpt/issues/1412
- [x] https://github.com/GoogleContainerTools/kpt/issues/2114
- [x] https://github.com/GoogleContainerTools/kpt/issues/2092
- [x] https://github.com/GoogleContainerTools/kpt/issues/1815

**Comment by phanimarupaka** [comment]
cc @mikebz @frankfarzan

**Comment by phanimarupaka** [comment]
@yhrn Can we have a timeline for getting your sign-off on this epic ? Are there any major action items for us to help you with smooth migration ? 

The support will continue even after you sign-off.

**Comment by yhrn** [comment]
@phanimarupaka I was added to this ticket without any heads up or additional context so I don't know what the expectations are. Am I signing off for all of Spotify or mainly as a Kpt user with some involved use cases? If it is the former then I need to pull some more people in. Also what would signing off mean? That I believe that migration will eventually be feasible given the direction of v1, that it already is feasible, that we have already migrated, something else?

I haven't had time to look into v1 that much other than reading docs and trying out various functions in the function catalog using v0. One obvious blocker is #1889. Another thing I need to understand is the details of v1 imperative vs declarative fn run. We currently have cases where we use some kind of mixed mode - `kpt fn source input-dir` -> `kpt fn run --fn-path` with fn configs annotated with the image, exec binary or Starlark source -> `kpt fn sink output-dir` and I'm not sure how that translates.

**Comment by phanimarupaka** [comment]
@yhrn Apologies for not providing more context in the issue description.

> @phanimarupaka I was added to this ticket without any heads up or additional context so I don't know what the expectations are. 

> Am I signing off for all of Spotify or mainly as a Kpt user with some involved use cases? If it is the former then I need to pull some more people in. 

Just for your team, or set of existing pre-v1 kpt packages you own. The aim here is to have a metric to measure some success with migrating existing pre-v1 kpt packages without major blockers.

> Also what would signing off mean? That I believe that migration will eventually be feasible given the direction of v1, that it already is feasible, that we have already migrated, something else?

Signing off doesn't mean you have completely migrated your packages and are production ready. It just means, you have done a decent POC using kpt v1, decided that it is feasible to migrate your packages and will be done eventually with no major blockers.

> 
> I haven't had time to look into v1 that much other than reading docs and trying out various functions in the function catalog using v0. One obvious blocker is #1889. 

I added it to the list of blockers. Thanks.

> Another thing I need to understand is the details of v1 imperative vs declarative fn run. We currently have cases where we use some kind of mixed mode - `kpt fn source input-dir` -> `kpt fn run --fn-path` with fn configs annotated with the image, exec binary or Starlark source -> `kpt fn sink output-dir` and I'm not sure how that translates.

You can go through this section for information https://kpt.dev/installation/migration?id=fn

**Comment by phanimarupaka** [comment]
Since the customers have different timelines for migrating their packages based on their priorities, it is not feasible to have it as the exit criteria for this epic. The work for migration from kpt team has been implemented and documented. There could be few issues/bugs filed by users as they migrate their packages but we can track it as individual issues and add them to appropriate milestones as opposed to tying them to this epic. So adjusting the exit criteria and closing this epic as the planned work is done and released.

cc @mikebz @frankfarzan
