### ISSUE TITLE
Epic: Function Target Selector

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2015]
Consider a package A that has subpackages B and C. It should be possible to declare a function F in package A, that operates on resources in:
- A, B, and C (current behavior)
- Only A
- Only B

Generalizing this, a function declaration in the `Kptfile` can have a target selector using different matching criteria:

- Matching a package (example above)
- Matching resources based on a combination of (Group, Kind, Namespace, Name)
- etc.

An example (Exact schema TBD):

```yaml
mutators:
   - image: gcr.io/kpt-fn/set-labels:v1
     configMap:
        - app: wordpress
     target:
        packages:
            - mysql
        kinds:
            - Deployment
```

This sets labels only on Deployments resources in the mysql subpackage (immediate child package).

This will be a purely additive change, so can be done in later milestones without breaking backwards compatibility.

Work Items:
- [x] Design doc([2418](https://github.com/GoogleContainerTools/kpt/issues/2418))
- [x] Implement base infrastructure, handle pruning([2439](https://github.com/GoogleContainerTools/kpt/issues/2439))
- [ ] Implement package selector([2440](https://github.com/GoogleContainerTools/kpt/issues/2440))
- [x] Implement GVKNN selectors([2441](https://github.com/GoogleContainerTools/kpt/issues/2441))
- [ ] Implement labels selector([2442](https://github.com/GoogleContainerTools/kpt/issues/2442))

Related issues: https://github.com/GoogleContainerTools/kpt/issues/988, https://github.com/GoogleContainerTools/kpt/issues/920

**Comment by karlkfi** [comment]
Probably also want to be able to filter by name, namespace, and label selectors.

**Comment by droot** [comment]
@karlkfi @morgante Thanks for the feedback on the filtering requirement. We are prioritizing this and will begin the work on this one soon.

**Comment by droot** [comment]
So selector machinery is in with most of the important selectors (GVKNN) that users requested. Rest selectors (package selector especially) will be addressed as an incremental change.
