### ISSUE TITLE
Prepare to switch to 1.0 branch

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2051]
We should prepare for the 1.0 branch (`next`) to become the main branch for development. To prepare for that, a few things need to be in place:

- [x] Make sure "old" kpt handles new packages gracefully by providing a helpful error message.
- [x] Make sure 1.0 kpt handles old packages gracefully by providing a helpful error message and directions for how to migrate.
- [x] Cut a new `main` branch from `next` and make it the default. As part of this, we need to make sure all CI/CD/release jobs continue to work. This also means tags for images and directories for artifacts must be updated.
- [x] Update installation docs
- [x] Update docs for both "old" and new kpt to clearly specify which version they pertain to (https://github.com/GoogleContainerTools/kpt/issues/1662).
- [x] README for main branch should be updated and include links to old docs.
- [x] Make sure the new kpt site is indexed instead of the old site (https://github.com/GoogleContainerTools/kpt/issues/1662).
- [x] Update the link on the kpt repo to point to the new kpt.dev site.
- [x] v0 branch: Fix CI/CD scripts. They should not release any artifacts as “latest” or “master” anymore. Update docs accordingly.
- [x] main branch: Fix CI/CD script. They should not release anything as “next” anymore. Update docs accordingly.
[main] Make a release.
- [x] Release v1 to homebrew and gcloud: https://github.com/GoogleContainerTools/kpt/issues/1842

**Comment by mikebz** [comment]
why not M4 when we are about to launch?

**Comment by frankfarzan** [comment]
This can be done before release 1.0 as the UX and documentation of 1.0-alpha will surpass 0.38 release before then and we want feedback before 1.0 release.

**Comment by frankfarzan** [comment]
At least a subset of the items here should be done in M3.
