### ISSUE TITLE
Setter Umbrella Issue

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#224]
- [x] make the field name optional #249 
- [x] support field path #250
- [x] have description per setter #251
- [x] de-dup setter metadata #252
- [x] replace partial setters with substitutions that aren't lossy #253
- [x] merge swagger.json OpenAPI with the line comment openapi #255
- [x] automatically create setters for substitutions #256 
- [x] merge openAPI when updating the kptfile #257 
- [x] support openAPI validations https://github.com/GoogleContainerTools/kpt/issues/631
- [x] Setter markers should refer to values https://github.com/GoogleContainerTools/kpt/issues/543
- [x] List substitutions from list-setters https://github.com/GoogleContainerTools/kpt/issues/323
- [x] Validate KptFile substitions and setters https://github.com/GoogleContainerTools/kpt/issues/550
- [x] support nested substitutions https://github.com/GoogleContainerTools/kpt/issues/551
- [x] mark field as required for apply https://github.com/GoogleContainerTools/kpt/issues/261
- [x] support `delete-setter` https://github.com/GoogleContainerTools/kpt/issues/258

## Automatically create setters for substitutions

when creating a substitution, check if the setters exist.  if they don't, then create them based off the pattern and value passed in

## support `delete-setter`

allow programatic deletion of setters

## merge openapi with per-field openapi

combine the per-field openapi with the global openapi

## Make field name optional

The field name for `create-setter` should be optional.  If unspecified, all fields with a value matching SETTER_VALUE should have the setter added.  If there is an existing setter, it should be replaced.

If `--partial` is specified, all fields with the SETTER_VALUE as a substring of the current value should have a partial setter created.  **If the SETTER_VALUE matches the full current value, a full setter should be created, regardless of the value of --partial.**

```sh
kpt cfg create-setter DIR SETTER_NAME SETTER_VALUE --type string
```

File: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/setters/addyaml.go#L59

## Move description and type into setter extension

Currently the description is per-field in the openapi.  The setters should each have their own description.

Update the FieldSetters and PartialField setters to have description and type, then use this when reading and writing setters:

https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fieldmeta/fieldmeta.go#L33

## De-dup the setter field meta

Currently the setters are written inline to each field, but this duplicates data that can get inconsistent.

Instead the setters should be written to the Kptfile, and referenced from inline.  E.g., instead of having the full setter as a comment, it should just have an openapi style ref: 

e.g. 

`# {"$ref": "#/definitions/io.k8s.config.setters.SETTER_NAME"}`

This would reference the setter specified in the Kptfile

We would want to parse the setters from the Kptfile as part of loading the openapi:

https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/openapi/openapi.go#L18

## Prevent lossy partial setters

Partial setters should be represented with a template and substitutions so repeated substrings don't cause issues

**Comment by frankfarzan** [comment]
@phanimarupaka Assigning to you to see if there' anything left here that's not been done or doesn't have a separate bug.

**Comment by phanimarupaka** [comment]
@frankfarzan I have included major feature requests we completed. There are few bugs which are not mentioned here(let me know if I should add). There are 3 open items in our road map for Q2(added to checklist) which will be completed soon.
