### ISSUE TITLE
Epic: Migrate packages from v1alpha2 to v1

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#2296]
We want all the kpt packages to be migrated to v1 no matter what version(v1alpha1, v1alpha2) they are on currently. `kpt 1.0.0-alpha11` release of kpt will drop support for all the pre-v1 version of kpt packages. Explicit error message will be displayed for smooth migration.

**Step 1**: Get approvals for all these tasks/PRs and DO NOT MERGE them
- [x] `kpt fn eval/render --output` and `kpt fn sink` should error out if the output directory already exists(https://github.com/GoogleContainerTools/kpt/pull/2215)
- [x] kpt fn eval --exec should support cmd+args (https://github.com/GoogleContainerTools/kpt/issues/2069)
- [x] Update kpt codebase to point to v1 and drop support for v1alpha2 (https://github.com/GoogleContainerTools/kpt/pull/2294)
- [x] Update kpt functions catalog codebase to point to v1 and drop support for v1alpha2. (https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/408)
- [x] Fix function should be smart to pack v1alpha1 and v1alpha2 and migrate to v1 (https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/398)
- [x] Fix function should move inline configMap to configPath (https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/398)
- [x] @mengqiy  Release v0.2 of fix function.

**Step2**: (Lock step)
- [x] @phanimarupaka Merge all approved PRs above. 
- [x] @mortent Release kpt 1.0.0-alpha11.
- [x] @phanimarupaka Release and update versions of nginx and wordpress in book.
- [x] @mengqiy Update each function example in respective release branches in kpt functions catalog. (https://github.com/GoogleContainerTools/kpt/issues/2299)

**Step3**: 
- [ ] Raise PR for Landing zone blueprints. (cc @morgante)

**Comment by frankfarzan** [comment]
> We want all the kpt packages to be migrated to v1 no matter what version(v1alpha1, v1alpha2) they are on currently. `kpt 1.0.0-alpha11` release of kpt will drop support for all the pre-v1 version of kpt packages. Explicit error message will be displayed for migration steps for smooth migration.
> 
> **Step 1**: Get approvals for all these tasks/PRs and merge them
> 
> * [ ]  Revert the reverted PR in kpt (#2294)
> * [ ]  Revert the reverted PR in kpt functions catalog. ([GoogleContainerTools/kpt-functions-catalog#400](https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/400))
> * [ ]  Update each function example in respective release branches in kpt functions catalog.
> * [x]  Fix function should be smart to pack v1alpha1 and v1alpha2 and migrate to v1 ([GoogleContainerTools/kpt-functions-catalog#398](https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/398))
> * [x]  Fix function should move inline configMap to configPath ([GoogleContainerTools/kpt-functions-catalog#398](https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/398))
> 
> **Step2**:
> 
> * [ ]  Release kpt 1.0.0-alpha11.
> * [ ]  Release v0.1.1 for fix function.
> 
> **Step 3**:
> 
> * [ ]  Release and update versions of nginx and wordpress in book.

This needs to be part of step 3 (Assuming all items in each step are in lock-step). Otherwise, there's a window where the documentation will be broken.

> * [ ]  Raise PR for Landing zone blueprints.

**Comment by frankfarzan** [comment]
I also suggest making the release with v1 CRDs beta: v1.0.0-beta.1. It's a major milestone.

**Comment by frankfarzan** [comment]
Let's discuss whether we want this release be called `v1.0.0-beta.1` instead of `v1.0.0-alpha.11`. It's a big deal given package formatting is guaranteed to be backwards compatible. Let's audit what's left in M3. @droot @mortent

**Comment by mortent** [comment]
I think we should call it `v1.0.0-beta.1`. The only item in M3 where I think there could be a discussion around adding something to the Kptfile format would be https://github.com/GoogleContainerTools/kpt/issues/1438, primarily due to the question about how the merge logic can distinguish between a pipeline for in-place vs out-place hydration. But I think we would be able to add this in a backwards-compatible way if needed.
