### ISSUE TITLE
Status Umbrella Issue

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#246]
- [ ] Handle status for all the major built-in types
- [ ] Compute status based on dependent/generated resources
- [ ] Support the standard conditions for CRDs
- [ ] Handle "common" types of conditions for CRDs
- [ ] Properly handle status for deletion of resources

**Comment by phanimarupaka** [comment]
@mortent What is the progress of this issue? Can we close this ?
