### ISSUE TITLE
Epic: Best practices and Idiomatic kpt package examples

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2541]
- [ ] kpt best practices finalized
- [x] Tenant factory package examples
- [x] Tenant factory use-case Tutorial (and demo)
