### ISSUE TITLE
Epic: kpt should support `variant constructor pattern`

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2808]
This is an umbrella issue to track all the sub tasks related to `variant constructor pattern`. Refer to [original issue](https://github.com/GoogleContainerTools/kpt/issues/2590) for details.

- [x] Finalize the design for `context generation hook`
- [ ] publish `go/kpt-variant-constructor-pattern` in `kpt` repo [in progress]
- [x] `set-namespace` to support use-case for tenant provisioning
- [x] Implement in support for including meta/local resources by default in `fn render`
- [x] Implement in support for including meta/local resources by default in `fn eval`
- [x] Implement `context generation` pipeline
- [ ] Vendor `source-gcloud-config` function as builtin
- [x] Audit all functions in `kpt-function-catalog` to ensure they support `variant construction` by default
- [x] Document the `variant constructor pattern` with examples and guides
- [ ] Implement [`source-gcloud-config` function](https://github.com/GoogleContainerTools/kpt/issues/2795) in the catalog [in progress](TODO)

**Comment by droot** [comment]
We have completed all the items that we scoped for this epic. so closing this one out.
