### ISSUE TITLE
Umbrella issue for Ghost package

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#3379]
- [ ] `set-labels` should not transform local-config manifests. 
    - version: v0.1.5
    - expected:  skip KRM resources with `config.kubernetes.io/local-config: "true"` label . 
    - Another solution: add an option `includeLocalConfig` in `SetLabels` function config. 
- [ ] `set-namespace:v0.4.1` does not accept resources of same GVKNN (different file path). v0.3.4 works well.
- [ ] latest `set-namespace` with origin gives too many warnings for raw manifests. This is annoying.

**Comment by yuwenma** [comment]
User experience compared to Helm:

- helm users are more easy to get started. They only edit `values.yaml` file (with enough comment, they can even only read that file). While in kpt, configurations are on KRM resource level, especially since we recommend using `configPath` over `configMap`, users cannot merely read a Kptfile.
- Enabling or disabling a group of resources in helm is easy (e.g. make the inline if condition to be false can skip the resource). How shall we let users disable a group of KRM resource (e.g. networkPolicy, ingress)
