### ISSUE TITLE
Polish kpt + kustomize + kubectl experience

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#407]
## P1 Kpt provides a polished experience for customizing and updating packages

- [x] Update: Correctly apply updates when names have been changed with substitutions
- [x] Update: Identify merge conflicts and provide messaging
- [ ] Customization: Support for propagating setters from nested packages
- [x] Update: Improved formatting
- [ ] Support for nested grouping objets, kustomization files, setters

## P1 Kpt live

- [ ] Live cycle directives

## P1 Kustomize has a polished experience and is integrated into kubectl + kpt

- [ ] Kustomize uses kpt libraries to keep comments, structure, extensibility, etc
- [ ] Kustomize uses OpenAPI to augment FieldSpecs and identify transformation targets
- [ ] Kustomize is integrated into kpt
- [ ] Kustomize is integrated into kubectl (latest)

**Comment by mikebz** [comment]
I think this is a large task which has been described in the roadmap here: https://github.com/GoogleContainerTools/kpt/blob/master/docs/ROADMAP.md, has a number of tasks already created and is also reflected in the kustomize tasks as well.  I believe a better way to track this is going to be to create a milestone.
